# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('optical', ['core'])
    module.source = [
        'model/optical-channel.cc',
        'model/optical-remote-channel.cc',
        'model/optical-net-device.cc',
        # 'model/mems-node.cc',        
        'helper/optical-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('optical')
    module_test.source = [
        'test/optical-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'optical'
    headers.source = [
        'model/optical-channel.h',
        'model/optical-remote-channel.h',
        'model/optical-net-device.h',
        # 'model/mems-node.h',        
        'model/mems-link-matrix.h',
        'helper/optical-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

